services:
  app:
    image: 'backend:latest'
    restart: always
    build:
      context: .
      no_cache: true
    container_name: app
    depends_on:
      - postgres-0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/advent_calendar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  postgres-0:
    image: postgres:alpine
    restart: always
    container_name: postgres-0
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: advent_calendar
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: ../advent_calendar_frontend
    volumes:
      - "../advent_calendar_frontend:/usr/src/app"
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

volumes:
  angularngixvolume:
  postgres-data:


